### ISSUE TITLE
[linuxbrew-bottles] Failed to download resource "openssl@1.1"

### ISSUE THREAD

**Issue by mumashanren** [tuna/tunasync-scripts#104]
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles/openssl%401.1-1.1.1h.x86_64_linux.bottle.tar.gz
curl: (22) The requested URL returned error: 404                              

Error: Failed to download resource "openssl@1.1"
Download failed: https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles/openssl%401.1-1.1.1h.x86_64_linux.bottle.tar.gz

But linuxbrew.bintray.com is ok

==> Downloading https://linuxbrew.bintray.com/bottles/openssl%401.1-1.1.1h.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/61/61bf82b4b62e07589dec1fdc9eb9eb053da01565581fb18dd5df6232182238ec?__gda__=exp=1606235004~hmac=e668bdb2312764a6996a5146431a77ac0b5acea782fe86812e34fefc47c74687&re

**Comment by ZenithalHourlyRate** [comment]
Dup of tuna/issues/issues/1057

**Comment by shankerwangmiao** [comment]
该问题已经处理。
