### ISSUE TITLE
请问下如果我只保留ubuntu16.04以上的版本，应该怎么写 `gen_ubuntu_exclude` 的思路呢。

### ISSUE THREAD

**Issue by xx-zhang** [tuna/tunasync-scripts#105]
-  请问下如果我只保留ubuntu16.04以上的版本，应该怎么写 `gen_ubuntu_exclude` 的思路呢。
-  同理，如果我只保留 centos/7 的，资源最大的地方应该是rpm包，是吧，那么这个rpm-url路径的exclude有什么思路呢。
- `exclude_file` 被识别是 endwith, 还是正则整个url路径

**Comment by xx-zhang** [comment]
我先关闭，谢谢能给出思路。

**Comment by shankerwangmiao** [comment]
没懂您要问啥。。。。。

**Comment by xx-zhang** [comment]
@shankerwangmiao 打扰您了，我已经解决了，就是只下载ubuntu18.04/ubuntu20.04不下载其他的版本，我后来使用 apt-sync 做到了。
