### ISSUE TITLE
msys2.sh using lftp command ，it  make the timestamp of local file is is different from the one of the file on sever

### ISSUE THREAD

**Issue by handsomeprince** [tuna/tunasync-scripts#13]
msys2.sh using lftp command ，it  make the timestamp of local file is is different from the one of the file on sever. I don't know how to make the timestamps same,maybe the lftp configure file is different. I need some help and tips.

**Comment by huiyiqun** [comment]
Why must you keep the timestamp identical?

Actually, most of our scripts do not ensure that assumption.

**Comment by huiyiqun** [comment]
A quick Google give me [this](https://stackoverflow.com/a/12817995), have you tried this?

**Comment by handsomeprince** [comment]
I am mirroring a folder from mirrors using lftp, like this
1、>   lftp https://opensource.apple.com             #connect successfully
2、>   mirror -c -v -n tarballs                    #useing 'mirror -c -v -n tarballs' command to mirror tarballs folder .The "tarballs" is a folder on server.'Is' command can't list it, but it exits really

3、when all have done, I find the timestamp of local file is is different from the one of the file on sever.

So , if I use this script, the timestamp of  file may be changed. But I have seen the file on tuna msys mirror sever keep the timestamp same with the remote,I am puzzled.Do you using this script to mirror msys software ? The reason Why  I MUST keep the timestamp same is using some command like rsync ,which could overwrite the different timestamp files  even if these files are same.

**Comment by huiyiqun** [comment]
There are exactly NO additional configuration. Our scripts are running in [this docker](https://github.com/tuna/tunasync-scripts/blob/master/Dockerfile), which use the default configuration of debian.

I guess maybe it's the server side (apple) that cause the issue, which do not expose the timestamp to lftp correctly.

**Comment by handsomeprince** [comment]
I used to mirror mysql from USTC sever using lftp on command line with interactive mode, and the same thing have happened. Maybe it is a bug. So I seek help from the Author of lftp software, waiting his response. Thank you all the same.
