### ISSUE TITLE
docker-ce 同步脚本在网络连接不正常时可能导致文件缺失

### ISSUE THREAD

**Issue by shankerwangmiao** [tuna/tunasync-scripts#15]
根据日志的记录，推测应该是当枚举文件的 python 脚本出现异常不能正常执行完毕时，导致列举的目录列表不全，尚未被列举出的目录和文件随后被同步脚本删除。

**Comment by bigeagle** [comment]
closed by 7bd1297d6ab42d15f5cd072160bebd9824f57875
