### ISSUE TITLE
How to set "TUNASYNC_WORKING_DIR" as a customize download folder

### ISSUE THREAD

**Issue by huanghaiqing1** [tuna/tunasync-scripts#164]
Hello, I clone tunasync-scripts to local by gh, and here I only want to sync part of repos by using bash file insde the script tar ball. For example, here I want to use proxmox.sh to rsync proxmox repos to local OS, how should I set variable TUNASYNC_WORKING_DIR in the script to a customize path. Is there any conf file to define TUNASYNC_WORKING_DIR in a central path? Currently I define the proxmox.sh script, but I don't want to change the structure the scripts pool inside tunasync-scripts fodler.

**Comment by shankerwangmiao** [comment]
Hi,

The scripts in tunasync-scripts are designed to be used with `tunasync`. `TUNASYNC_WORKING_DIR`, as well as other environment variables, is defined by `tunasync` when starting the script.

If you would like to use the scripts alone, you may define the variables before calling them. For example:

``` bash
TUNASYNC_WORKING_DIR=/path/to/target /path/to/tunasync-scripts/proxmox.sh
```
