### ISSUE TITLE
Detail example when use yum-sync.py

### ISSUE THREAD

**Issue by huanghaiqing1** [tuna/tunasync-scripts#174]
Hello, I'm still not clear about the actual usage for yum-sync.py. It's example is as below shows. But if I want to mirror ONLY 
 "aarch64" part from https://mirrors.tuna.tsinghua.edu.cn/centos-stream/9-stream/BaseOS/"  to local "/root/patch/aarch64". How should I assign the detail parameters after yum-sync.py? 

autoyast:~/patch/tunasync-scripts #  次世代 -> python3 yum-sync.py -h
usage: yum-sync.py [-h] [--download-repodata] [--pass-arch-to-reposync]
                   base_url os_version component arch repo_name working_dir

positional arguments:
  base_url              base URL
  os_version            e.g. 7-8,9
  component             e.g. mysql56-community,mysql57-community
  arch                  e.g. x86_64,aarch64
  repo_name             e.g. @{comp}-el@{os_ver}
  working_dir           working directory

optional arguments:
  -h, --help            show this help message and exit
  --download-repodata   download repodata files instead of generating them
  --pass-arch-to-reposync
                        pass --arch to reposync to further filter packages by
                        'arch' field in metadata (NOT recommended, prone to
                        missing packages in some repositories, e.g. mysql)

**Comment by shankerwangmiao** [comment]
For your particular case, I suggest rsync rather than using `yum-sync.py` via http.

The following command will fit your requirement:

```
rsync -a --delete --delete-after --delay-updates --progress rsync://mirrors.tuna.tsinghua.edu.cn/centos-stream/9-stream/BaseOS/aarch64/  /root/patch/aarch64/
```

**Comment by huanghaiqing1** [comment]
Thanks for the quick support. For your command, is it an everytime full mirror? I mean everytime it use rsync to scan all the files. Does it have same sync speed like my current solution[by opensuse rmt-cli]? On Mar 3, 2024, at 9:57 PM, Miao Wang ***@***.***> wrote: For your particular case, I suggest rsync rather than using yum-sync.py via http. The following command will fit your requirement: rsync -a --delete --delete-after --delay-updates --progress rsync://mirrors.tuna.tsinghua.edu.cn/centos-stream/9-stream/BaseOS/aarch64/ /root/patch/aarch64/ — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by shankerwangmiao** [comment]
Rsync is designed for sync files in directories and we always recommend rsync rather than using http since it can seldom go wrong and saves resource on both client side and server side.
