### ISSUE TITLE
能添加如何使用 tunasync-scripts 的说明吗？

### ISSUE THREAD

**Issue by JohnWongCHN** [tuna/tunasync-scripts#175]
已在内网部署 tunasync 服务，对于支持 rsync 协议的镜像已经同步了一些站点，现在想添加同步不支持 rsync 的镜像。

已做的尝试：
1. 运行 tunasync 服务的用户已添加进 docker 用户组
2. docker 运行 tunathu/tunasync-scripts 容器，容器内挂载了 /home/tunasync-scripts，也添加了脚本
3. 添加了对应的 worker 配置

但是碰到这样的错误

`
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/home/tunasync-scripts/kylin-linux-advanced-server.sh": stat /home/tunasync-scripts/kylin-linux-advanced-server.sh: no such file or directory: unknown.
`

现在没有头绪，不知道如何排障了。

**Comment by shankerwangmiao** [comment]
`tunathu/tunasync-scripts` 容器镜像提供了 tunasync-scripts 中脚本的运行环境和其依赖。在使用时，可以将  tunasync-scripts 目录挂载到容器中，再执行脚本。这样在修改脚本后，不需要重新构建容器镜像。

具体使用方法是，假定脚本存储在 `/path/tunasync-scripts` 中，名称为 `foo.sh`，在 `worker.conf` 的 `[docker]` 小节中，增加如下配置项：

```toml
[docker]
enable = true
volumes = [
        "/path/tunasync-scripts:/home/scripts:ro", // 表示所有使用 docker 同步的任务，都挂载此目录
]
```

在需要使用同步脚本和 docker 的镜像中增加如下配置

```
[[mirrors]]
// ...  name、interval、upstream 等不变
provider = "command" //只有 command 才能使用 docker，rsync 等其它的不支持
command = "/home/scripts/foo.sh"  //填写脚本在容器中的路径
docker_image = "tunathu/tunasync-scripts:latest" //要使用的 docker 镜像的名称，如果不配置此项，则直接在本机执行，不使用 docker
```
