### ISSUE TITLE
atp-sync.py现在还能正常使用吗，我自定义下载ubuntu 的focal的main仓库，客户段使用这个下载好的私有仓库报错。

### ISSUE THREAD

**Issue by IENR** [tuna/tunasync-scripts#176]
使用默认的不经过修改的apt-sync文件，然后：
python3 apt-sync.py https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal main amd64 /data/

同步下载完成后，客户端使用这个私有仓库同步的时候，提示mani仓库的cnf文件夹，i18n等文件缺少。

尝试修改apt-sync文件中的ARCH_NO_PKGIDX变量，重新同步，也没有同步上面cnf这几个文件夹

**Comment by shankerwangmiao** [comment]
目前 apt-sync 脚本对较复杂的仓库支持得还不够好。建议您使用 rsync 同步。
