### ISSUE TITLE
Add timeout and retry when using requests

### ISSUE THREAD

**Issue by shankerwangmiao** [tuna/tunasync-scripts#35]
https://github.com/tuna/tunasync-scripts/blob/a57f978678b7f42c53ac448b753ac46dfdce3269/anaconda.py#L135

https://github.com/tuna/tunasync-scripts/blob/a57f978678b7f42c53ac448b753ac46dfdce3269/anaconda.py#L150

https://github.com/tuna/tunasync-scripts/blob/a57f978678b7f42c53ac448b753ac46dfdce3269/docker-ce.py#L50

https://github.com/tuna/tunasync-scripts/blob/a57f978678b7f42c53ac448b753ac46dfdce3269/docker-ce.py#L104

https://2.python-requests.org//zh_CN/latest/user/advanced.html#timeout

**Comment by z4yx** [comment]
done
