### ISSUE TITLE
intel channel 404

### ISSUE THREAD

**Issue by sheljoy** [tuna/tunasync-scripts#38]
~/.condarc　配置如下：
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/fastai/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults

show_channel_urls: true

default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r

custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  intel: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud

－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
出现404

Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: intel
  channel url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/intel
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

**Comment by shankerwangmiao** [comment]
这个问题在 https://github.com/tuna/tunasync-scripts/commit/942fea954d400bb16943335b6cc22f686c71eed5 中被修复，请等待同步完成后就可以正常使用了。

**Comment by shankerwangmiao** [comment]
应该可以使用了，如果还有问题的话，请 reopen。
