### ISSUE TITLE
Stackage: new snapshot format

### ISSUE THREAD

**Issue by dramforever** [tuna/tunasync-scripts#50]
- https://www.stackage.org/blog/2019/07/new-snapshot-format
- https://groups.google.com/forum/#!topic/tuna-general/ANHyriDGxFw

暂时没太看懂该干啥，先开个 issue track 一下

**Comment by dramforever** [comment]
新增的应该是 <https://github.com/commercialhaskell/stackage-snapshots/>，但是问题是并没有办法配置 Stack 使用别的来源的这个 repo。刚看了一下 Stack 文档里面 `lts-*` 和 `nightly-*` 是指向 GitHub 的缩写，代码里（准确地说是 Pantry 库代码里）好像是写死的 URL，似乎是个问题，不过可能可以先 clone 下来再说？

https://github.com/commercialhaskell/pantry/blob/a5e52724b3d3ad8997942ab44050b49c5ad34ea7/src/Pantry/Types.hs#L1889-L1905

**Comment by dramforever** [comment]
[Pantry 写死的](https://docs.haskellstack.org/en/stable/pantry/#snapshot-location) `lts-*` 和 `nightly-*` 指向 GitHub，所以可能还没办法替换，但是大概可以把 https://github.com/commercialhaskell/stackage-snapshots/ clone 下来用着

**Comment by dramforever** [comment]
所以，进展是有人把那个改成可配置的功能做了，等这个什么时候 merge 了 release 了 https://github.com/commercialhaskell/stack/pull/5281 ，用 git 同步 https://github.com/commercialhaskell/stackage-snapshots/ 然后配个 `snapshot-location-base` 应该就可以访问到了

**Comment by z4yx** [comment]
好耶，tuna/issues#784 有望解决了

**Comment by z4yx** [comment]
上游已合并。我们是不是只需要把同步上述 git 仓库，把仓库内容发布到 https://mirrors.tuna.tsinghua.edu.cn/stackage/stackage-snapshots/ 就可以了？

**Comment by dramforever** [comment]
看了下感觉应该是发布到哪儿都行，然后需要加一些配置。如果没什么问题的话我觉得可以先同步着，万一我弄之前有谁试成功了，没准还能 pr 个配置呢。
