### ISSUE TITLE
pypi脚本没有遵守tunasync upstream的配置

### ISSUE THREAD

**Issue by zxkane** [tuna/tunasync-scripts#51]
按[tunasync的代码](https://github.com/tuna/tunasync/blob/10251895426ff2d0e804f7ce8f2f9fe4cbed2c48/worker/cmd_provider.go#L79)，upstream通过环境变量`TUNASYNC_UPSTREAM_URL`传入。当前`pypi.sh`使用的变量是`TUNASYNC_UPSTREAM`

**Comment by z4yx** [comment]
感谢！已修复。
