### ISSUE TITLE
so now there is a github-release entry ， how can I use this sync a repo‘s release thing

### ISSUE THREAD

**Issue by smile921** [tuna/tunasync-scripts#52]
I have tried https://mirrors.tuna.tsinghua.edu.cn/github-release/hovancik/stretchly
but unluckily got 404 。
So how this work ？ How can I use it ？Is there a guide

**Comment by z4yx** [comment]
It can not mirror all repositories on Github. Please submit a request on https://github.com/tuna/issues/issues if you want a new mirror.
