### ISSUE TITLE
有必要增加GC功能的同步脚本

### ISSUE THREAD

**Issue by z4yx** [tuna/tunasync-scripts#55]
目前发现一些镜像更新快，小文件多，无法手工清理旧版本文件，有必要增加扫描并清理文件的功能。

- [x] homebrew-bottle-mirror
- [x] anaconda.py
- [x] pub-mirror
- [x] flutter.sh
- [x] nix-channels.py
- [x] rustup-mirror

Ref:

- huiyiqun/pub-mirror#6

**Comment by dramforever** [comment]
#56 would fix nix-channels
