### ISSUE TITLE
本地同步 flutter 镜像后发现少文件，如何处理？

### ISSUE THREAD

**Issue by kassadin** [tuna/tunasync-scripts#63]
https://mirrors.tuna.tsinghua.edu.cn/flutter/flutter_infra/flutter/9e6314d348f9b5521e3c66856324d7a9c4a928c9/android-x86/
网页查看为空目录

但是https://mirrors.tuna.tsinghua.edu.cn/flutter/flutter_infra/flutter/9e6314d348f9b5521e3c66856324d7a9c4a928c9/android-x86/artifacts.zip 可以下载

对比原始仓库 https://console.cloud.google.com/storage/browser/flutter_infra/flutter/9e6314d348f9b5521e3c66856324d7a9c4a928c9/android-x86/ 是有文件的

**Comment by z4yx** [comment]
你是用的什么版本的flutter？
我们现在的脚本没有同步beta/dev channel，你说的这个engine目录是历史遗留的，来自flutter-io.cn。

**Comment by kassadin** [comment]
哦，了解，这个是 beta 版本的。

开发过程会来回切 stable 和 beta 提前采坑，所以想本地搭一下镜像。
