### ISSUE TITLE
aosp.sh    git repack -a -b -d error: unknown switch `b'

### ISSUE THREAD

**Issue by handsomeprince** [tuna/tunasync-scripts#66]
When I run aosp.sh , command **'git repack -a -b -d'** will give a error like this:
         git repack -a -b -d error: unknown switch `b'
I think maybe my git(git version 1.8.3.1) is newer or older than yours, and option '-b' is abandoned.
Why not use 'git gc'? Do you have any other considerations?

**Comment by z4yx** [comment]
The bitmap feature was added since Git 2.0.
ref: https://kscherer.github.io/git/2015/05/15/git-and-bitmapsv

**Comment by handsomeprince** [comment]
@z4yx thank U
