### ISSUE TITLE
Use create_repo and apt-mirror to sync nodesource instead of lftp

### ISSUE THREAD

**Issue by shankerwangmiao** [tuna/tunasync-scripts#86]
Currently, `deb_14.x/pool/main/n/nodejs/nodejs_14.8.0-deb-1nodesource1_amd64.deb` exists on the upstream server. However, it does not show up in  https://deb.nodesource.com/node_14.x/pool/main/n/nodejs/ 

https://github.com/tuna/tunasync-scripts/blob/d5f2142cf20143efec33ac79ed91028bce049192/nodesource.sh#L3-L20

**Comment by shankerwangmiao** [comment]
ref: https://github.com/tuna/issues/issues/929

**Comment by z4yx** [comment]
nodesource has been removed
